### PR TITLE
Fix modprobe command usage.

### PR DESCRIPTION
**Pull request by john-gress**

### CODE REVIEW

**Comment by KjellKod** [comment]
Looks OK. Why the removal of the .ko?

**Comment by ghost** [comment]
:+1: @KjellKod if i'm not mistaken modprobe looks through a generated list of modules, not filenames? so the .ko is not needed

**Comment by ghost** [comment]
insmod is the one that takes a .ko

**Comment by craig-cogdill** [comment]
:+1:

**Comment by john-gress** [comment]
@KjellKod, it doesn't work with the .ko.

**Comment by KjellKod** [comment]
@Yannick. U are right!

**Pull request merged**
